# Generated by Django 3.2.2 on 2022-03-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
