# Generated by Django 3.2.2 on 2022-03-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220316_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='feature_img/%Y/%m/%d'),
        ),
    ]
